[package]
name = "ucharm-cli"
description = "Command-line interface for μcharm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sha2 = "0.11"
ucharm-format = { path = "../ucharm-format" }

[[bin]]
name = "ucharm"
path = "src/main.rs"

[lints]
workspace = true
