/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct py_OpaqueName {
    _unused: [u8; 0],
}
#[doc = " A pointer that represents a python identifier. For fast name resolution."]
pub type py_Name = *mut py_OpaqueName;
#[doc = " An integer that represents a python type. `0` is invalid."]
pub type py_Type = i16;
#[doc = " A 64-bit integer type. Corresponds to `int` in python."]
pub type py_i64 = i64;
#[doc = " A 64-bit floating-point type. Corresponds to `float` in python."]
pub type py_f64 = f64;
#[doc = " A generic destructor function."]
pub type py_Dtor = ::core::option::Option<unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void)>;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct py_TValue {
    pub type_: py_Type,
    pub is_ptr: bool,
    pub extra: ::core::ffi::c_int,
    pub __bindgen_anon_1: py_TValue__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union py_TValue__bindgen_ty_1 {
    pub _i64: i64,
    pub _chars: [::core::ffi::c_char; 16usize],
}
#[doc = " A generic reference to a python object."]
pub type py_Ref = *mut py_TValue;
#[doc = " A reference which has the same lifespan as the python object."]
pub type py_ObjectRef = *mut py_TValue;
#[doc = " A global reference which has the same lifespan as the VM."]
pub type py_GlobalRef = *mut py_TValue;
#[doc = " A specific location in the value stack of the VM."]
pub type py_StackRef = *mut py_TValue;
#[doc = " An item reference to a container object. It invalidates when the container is modified."]
pub type py_ItemRef = *mut py_TValue;
#[doc = " An output reference for returning a value. Only use this for function arguments."]
pub type py_OutRef = *mut py_TValue;
#[doc = " Native function signature.\n @param argc number of arguments.\n @param argv array of arguments. Use `py_arg(i)` macro to get the i-th argument.\n @return `true` if the function is successful or `false` if an exception is raised."]
pub type py_CFunction = ::core::option::Option<
    unsafe extern "C" fn(argc: ::core::ffi::c_int, argv: py_StackRef) -> bool,
>;
pub const py_CompileMode_EXEC_MODE: py_CompileMode = 0;
pub const py_CompileMode_EVAL_MODE: py_CompileMode = 1;
pub const py_CompileMode_SINGLE_MODE: py_CompileMode = 2;
pub const py_CompileMode_RELOAD_MODE: py_CompileMode = 3;
#[doc = " Python compiler modes.\n + `EXEC_MODE`: for statements.\n + `EVAL_MODE`: for expressions.\n + `SINGLE_MODE`: for REPL or jupyter notebook execution.\n + `RELOAD_MODE`: for reloading a module without allocating new types if possible."]
pub type py_CompileMode = ::core::ffi::c_uint;
unsafe extern "C" {
    #[doc = " Initialize pocketpy and the default VM."]
    pub fn py_initialize();
}
unsafe extern "C" {
    #[doc = " Finalize pocketpy and free all VMs. This opearation is irreversible.\n After this call, you cannot use any function from this header anymore."]
    pub fn py_finalize();
}
unsafe extern "C" {
    #[doc = " Set `sys.argv`. Used for storing command-line arguments."]
    pub fn py_sys_setargv(argc: ::core::ffi::c_int, argv: *mut *mut ::core::ffi::c_char);
}
unsafe extern "C" {
    #[doc = " Compile a source string into a code object.\n Use python's `exec()` or `eval()` to execute it."]
    pub fn py_compile(
        source: *const ::core::ffi::c_char,
        filename: *const ::core::ffi::c_char,
        mode: py_CompileMode,
        is_dynamic: bool,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Run a source string.\n @param source source string.\n @param filename filename (for error messages).\n @param mode compile mode. Use `EXEC_MODE` for statements `EVAL_MODE` for expressions.\n @param module target module. Use NULL for the main module.\n @return `true` if the execution is successful or `false` if an exception is raised."]
    pub fn py_exec(
        source: *const ::core::ffi::c_char,
        filename: *const ::core::ffi::c_char,
        mode: py_CompileMode,
        module: py_Ref,
    ) -> bool;
}
unsafe extern "C" {
    #[doc = " Create an `int` object."]
    pub fn py_newint(arg1: py_OutRef, arg2: py_i64);
}
unsafe extern "C" {
    #[doc = " Create a `float` object."]
    pub fn py_newfloat(arg1: py_OutRef, arg2: py_f64);
}
unsafe extern "C" {
    #[doc = " Create a `bool` object."]
    pub fn py_newbool(arg1: py_OutRef, arg2: bool);
}
unsafe extern "C" {
    #[doc = " Create a `str` object with `n` UNINITIALIZED bytes plus `'\\0'`."]
    pub fn py_newstrn(arg1: py_OutRef, arg2: ::core::ffi::c_int) -> *mut ::core::ffi::c_char;
}
unsafe extern "C" {
    #[doc = " Create a `bytes` object with `n` UNINITIALIZED bytes."]
    pub fn py_newbytes(arg1: py_OutRef, n: ::core::ffi::c_int) -> *mut ::core::ffi::c_uchar;
}
unsafe extern "C" {
    #[doc = " Create a `None` object."]
    pub fn py_newnone(arg1: py_OutRef);
}
unsafe extern "C" {
    #[doc = " Create a new object.\n @param out output reference.\n @param type type of the object.\n @param slots number of slots. Use `-1` to create a `__dict__`.\n @param udsize size of your userdata.\n @return pointer to the userdata."]
    pub fn py_newobject(
        out: py_OutRef,
        type_: py_Type,
        slots: ::core::ffi::c_int,
        udsize: ::core::ffi::c_int,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    #[doc = " Convert a null-terminated string to a name."]
    pub fn py_name(arg1: *const ::core::ffi::c_char) -> py_Name;
}
unsafe extern "C" {
    #[doc = " Bind a function to the object via \"decl-based\" style.\n @param obj the target object.\n @param sig signature of the function. e.g. `add(x, y)`.\n @param f function to bind."]
    pub fn py_bind(obj: py_Ref, sig: *const ::core::ffi::c_char, f: py_CFunction);
}
unsafe extern "C" {
    #[doc = " Bind a method to type via \"argc-based\" style.\n @param type the target type.\n @param name name of the method.\n @param f function to bind."]
    pub fn py_bindmethod(type_: py_Type, name: *const ::core::ffi::c_char, f: py_CFunction);
}
unsafe extern "C" {
    #[doc = " Bind a function to the object via \"argc-based\" style.\n @param obj the target object.\n @param name name of the function.\n @param f function to bind."]
    pub fn py_bindfunc(obj: py_Ref, name: *const ::core::ffi::c_char, f: py_CFunction);
}
unsafe extern "C" {
    #[doc = " Convert an `int` object in python to `int64_t`."]
    pub fn py_toint(arg1: py_Ref) -> py_i64;
}
unsafe extern "C" {
    #[doc = " Convert a `float` object in python to `double`."]
    pub fn py_tofloat(arg1: py_Ref) -> py_f64;
}
unsafe extern "C" {
    #[doc = " Cast a `int` or `float` object in python to `double`.\n If successful, return true and set the value to `out`.\n Otherwise, return false and raise `TypeError`."]
    pub fn py_castfloat(arg1: py_Ref, out: *mut py_f64) -> bool;
}
unsafe extern "C" {
    #[doc = " Cast a `int` object in python to `int64_t`."]
    pub fn py_castint(arg1: py_Ref, out: *mut py_i64) -> bool;
}
unsafe extern "C" {
    #[doc = " Convert a `bool` object in python to `bool`."]
    pub fn py_tobool(arg1: py_Ref) -> bool;
}
unsafe extern "C" {
    #[doc = " Convert a user-defined object to its userdata."]
    pub fn py_touserdata(arg1: py_Ref) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    #[doc = " Convert a `str` object in python to char array."]
    pub fn py_tostrn(arg1: py_Ref, size: *mut ::core::ffi::c_int) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    #[doc = " Convert a `bytes` object in python to char array."]
    pub fn py_tobytes(arg1: py_Ref, size: *mut ::core::ffi::c_int) -> *mut ::core::ffi::c_uchar;
}
unsafe extern "C" {
    #[doc = " Create a new type.\n @param name name of the type.\n @param base base type.\n @param module module where the type is defined. Use `NULL` for built-in types.\n @param dtor destructor function. Use `NULL` if not needed."]
    pub fn py_newtype(
        name: *const ::core::ffi::c_char,
        base: py_Type,
        module: py_GlobalRef,
        dtor: py_Dtor,
    ) -> py_Type;
}
unsafe extern "C" {
    #[doc = " Check if the object is exactly the given type."]
    pub fn py_istype(arg1: py_Ref, arg2: py_Type) -> bool;
}
unsafe extern "C" {
    #[doc = " Get the type of the object."]
    pub fn py_typeof(self_: py_Ref) -> py_Type;
}
unsafe extern "C" {
    #[doc = " Check if the object is an instance of the given type."]
    pub fn py_isinstance(obj: py_Ref, type_: py_Type) -> bool;
}
unsafe extern "C" {
    #[doc = " Search the magic method from the given type to the base type.\n Return `NULL` if not found."]
    pub fn py_tpfindmagic(arg1: py_Type, name: py_Name) -> py_GlobalRef;
}
unsafe extern "C" {
    #[doc = " Get the type object of the given type."]
    pub fn py_tpobject(type_: py_Type) -> py_GlobalRef;
}
unsafe extern "C" {
    #[doc = " Get the i-th register.\n All registers are located in a contiguous memory."]
    pub fn py_getreg(i: ::core::ffi::c_int) -> py_GlobalRef;
}
unsafe extern "C" {
    #[doc = " Get the last return value.\n Please note that `py_retval()` cannot be used as input argument."]
    pub fn py_retval() -> py_GlobalRef;
}
unsafe extern "C" {
    #[doc = " Get an item from the object's `__dict__`.\n Return `NULL` if not found."]
    pub fn py_getdict(self_: py_Ref, name: py_Name) -> py_ItemRef;
}
unsafe extern "C" {
    #[doc = " Set an item to the object's `__dict__`."]
    pub fn py_setdict(self_: py_Ref, name: py_Name, val: py_Ref);
}
unsafe extern "C" {
    #[doc = " Get the i-th slot of the object.\n The object must have slots and `i` must be in valid range."]
    pub fn py_getslot(self_: py_Ref, i: ::core::ffi::c_int) -> py_ObjectRef;
}
unsafe extern "C" {
    #[doc = " Set the i-th slot of the object."]
    pub fn py_setslot(self_: py_Ref, i: ::core::ffi::c_int, val: py_Ref);
}
unsafe extern "C" {
    #[doc = " Get the i-th object from the top of the stack.\n `i` should be negative, e.g. (-1) means TOS."]
    pub fn py_peek(i: ::core::ffi::c_int) -> py_StackRef;
}
unsafe extern "C" {
    #[doc = " Pop an object from the stack."]
    pub fn py_pop();
}
unsafe extern "C" {
    #[doc = " Get a temporary variable from the stack."]
    pub fn py_pushtmp() -> py_StackRef;
}
unsafe extern "C" {
    #[doc = " Call a function.\n It prepares the stack and then performs a `vectorcall(argc, 0, false)`.\n The result will be set to `py_retval()`.\n The stack remains unchanged if successful."]
    pub fn py_call(f: py_Ref, argc: ::core::ffi::c_int, argv: py_Ref) -> bool;
}
unsafe extern "C" {
    #[doc = " Call a type to create a new instance."]
    pub fn py_tpcall(type_: py_Type, argc: ::core::ffi::c_int, argv: py_Ref) -> bool;
}
unsafe extern "C" {
    #[doc = " Python equivalent to `lhs is rhs`."]
    pub fn py_isidentical(arg1: py_Ref, arg2: py_Ref) -> bool;
}
unsafe extern "C" {
    #[doc = " Compare two objects.\n 1: lhs == rhs, 0: lhs != rhs, -1: error"]
    pub fn py_equal(lhs: py_Ref, rhs: py_Ref) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Compare two objects.\n 1: lhs < rhs, 0: lhs >= rhs, -1: error"]
    pub fn py_less(lhs: py_Ref, rhs: py_Ref) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Python equivalent to `getattr(self, name)`."]
    pub fn py_getattr(self_: py_Ref, name: py_Name) -> bool;
}
unsafe extern "C" {
    #[doc = " Get a module by path."]
    pub fn py_getmodule(path: *const ::core::ffi::c_char) -> py_GlobalRef;
}
unsafe extern "C" {
    #[doc = " Create a new module."]
    pub fn py_newmodule(path: *const ::core::ffi::c_char) -> py_GlobalRef;
}
unsafe extern "C" {
    #[doc = " Import a module.\n The result will be set to `py_retval()`.\n -1: error, 0: not found, 1: success"]
    pub fn py_import(path: *const ::core::ffi::c_char) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Check if the unhandled exception is an instance of the given type.\n If match, the exception will be stored in `py_retval()`."]
    pub fn py_matchexc(type_: py_Type) -> bool;
}
unsafe extern "C" {
    #[doc = " Clear the unhandled exception.\n @param p0 the unwinding point. Use `NULL` if not needed."]
    pub fn py_clearexc(p0: py_StackRef);
}
unsafe extern "C" {
    #[doc = " Print the unhandled exception."]
    pub fn py_printexc();
}
unsafe extern "C" {
    #[doc = " Raise an exception by type and message. Always return false."]
    pub fn py_exception(type_: py_Type, fmt: *const ::core::ffi::c_char, ...) -> bool;
}
unsafe extern "C" {
    #[doc = " Create a `tuple` with `n` UNINITIALIZED elements.\n You should initialize all elements before using it."]
    pub fn py_newtuple(arg1: py_OutRef, n: ::core::ffi::c_int) -> py_ObjectRef;
}
unsafe extern "C" {
    pub fn py_tuple_getitem(self_: py_Ref, i: ::core::ffi::c_int) -> py_ObjectRef;
}
unsafe extern "C" {
    pub fn py_tuple_setitem(self_: py_Ref, i: ::core::ffi::c_int, val: py_Ref);
}
unsafe extern "C" {
    pub fn py_tuple_len(self_: py_Ref) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Create an empty `list`."]
    pub fn py_newlist(arg1: py_OutRef);
}
unsafe extern "C" {
    pub fn py_list_getitem(self_: py_Ref, i: ::core::ffi::c_int) -> py_ItemRef;
}
unsafe extern "C" {
    pub fn py_list_setitem(self_: py_Ref, i: ::core::ffi::c_int, val: py_Ref);
}
unsafe extern "C" {
    pub fn py_list_delitem(self_: py_Ref, i: ::core::ffi::c_int);
}
unsafe extern "C" {
    pub fn py_list_len(self_: py_Ref) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn py_list_swap(self_: py_Ref, i: ::core::ffi::c_int, j: ::core::ffi::c_int);
}
unsafe extern "C" {
    pub fn py_list_append(self_: py_Ref, val: py_Ref);
}
unsafe extern "C" {
    #[doc = " Create an empty `dict`."]
    pub fn py_newdict(arg1: py_OutRef);
}
unsafe extern "C" {
    #[doc = " -1: error, 0: not found, 1: found"]
    pub fn py_dict_getitem(self_: py_Ref, key: py_Ref) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " true: success, false: error"]
    pub fn py_dict_setitem(self_: py_Ref, key: py_Ref, val: py_Ref) -> bool;
}
unsafe extern "C" {
    #[doc = " true: success, false: error"]
    pub fn py_dict_apply(
        self_: py_Ref,
        f: ::core::option::Option<
            unsafe extern "C" fn(key: py_Ref, val: py_Ref, ctx: *mut ::core::ffi::c_void) -> bool,
        >,
        ctx: *mut ::core::ffi::c_void,
    ) -> bool;
}
pub const py_PredefinedType_tp_nil: py_PredefinedType = 0;
pub const py_PredefinedType_tp_object: py_PredefinedType = 1;
pub const py_PredefinedType_tp_type: py_PredefinedType = 2;
pub const py_PredefinedType_tp_int: py_PredefinedType = 3;
pub const py_PredefinedType_tp_float: py_PredefinedType = 4;
pub const py_PredefinedType_tp_bool: py_PredefinedType = 5;
pub const py_PredefinedType_tp_str: py_PredefinedType = 6;
pub const py_PredefinedType_tp_str_iterator: py_PredefinedType = 7;
pub const py_PredefinedType_tp_list: py_PredefinedType = 8;
pub const py_PredefinedType_tp_tuple: py_PredefinedType = 9;
pub const py_PredefinedType_tp_list_iterator: py_PredefinedType = 10;
pub const py_PredefinedType_tp_tuple_iterator: py_PredefinedType = 11;
pub const py_PredefinedType_tp_slice: py_PredefinedType = 12;
pub const py_PredefinedType_tp_range: py_PredefinedType = 13;
pub const py_PredefinedType_tp_range_iterator: py_PredefinedType = 14;
pub const py_PredefinedType_tp_module: py_PredefinedType = 15;
pub const py_PredefinedType_tp_function: py_PredefinedType = 16;
pub const py_PredefinedType_tp_nativefunc: py_PredefinedType = 17;
pub const py_PredefinedType_tp_boundmethod: py_PredefinedType = 18;
pub const py_PredefinedType_tp_super: py_PredefinedType = 19;
pub const py_PredefinedType_tp_BaseException: py_PredefinedType = 20;
pub const py_PredefinedType_tp_Exception: py_PredefinedType = 21;
pub const py_PredefinedType_tp_bytes: py_PredefinedType = 22;
pub const py_PredefinedType_tp_namedict: py_PredefinedType = 23;
pub const py_PredefinedType_tp_locals: py_PredefinedType = 24;
pub const py_PredefinedType_tp_code: py_PredefinedType = 25;
pub const py_PredefinedType_tp_dict: py_PredefinedType = 26;
pub const py_PredefinedType_tp_dict_iterator: py_PredefinedType = 27;
pub const py_PredefinedType_tp_property: py_PredefinedType = 28;
pub const py_PredefinedType_tp_star_wrapper: py_PredefinedType = 29;
pub const py_PredefinedType_tp_staticmethod: py_PredefinedType = 30;
pub const py_PredefinedType_tp_classmethod: py_PredefinedType = 31;
pub const py_PredefinedType_tp_NoneType: py_PredefinedType = 32;
pub const py_PredefinedType_tp_NotImplementedType: py_PredefinedType = 33;
pub const py_PredefinedType_tp_ellipsis: py_PredefinedType = 34;
pub const py_PredefinedType_tp_generator: py_PredefinedType = 35;
pub const py_PredefinedType_tp_SystemExit: py_PredefinedType = 36;
pub const py_PredefinedType_tp_KeyboardInterrupt: py_PredefinedType = 37;
pub const py_PredefinedType_tp_StopIteration: py_PredefinedType = 38;
pub const py_PredefinedType_tp_SyntaxError: py_PredefinedType = 39;
pub const py_PredefinedType_tp_RecursionError: py_PredefinedType = 40;
pub const py_PredefinedType_tp_OSError: py_PredefinedType = 41;
pub const py_PredefinedType_tp_NotImplementedError: py_PredefinedType = 42;
pub const py_PredefinedType_tp_TypeError: py_PredefinedType = 43;
pub const py_PredefinedType_tp_IndexError: py_PredefinedType = 44;
pub const py_PredefinedType_tp_ValueError: py_PredefinedType = 45;
pub const py_PredefinedType_tp_RuntimeError: py_PredefinedType = 46;
pub const py_PredefinedType_tp_TimeoutError: py_PredefinedType = 47;
pub const py_PredefinedType_tp_ZeroDivisionError: py_PredefinedType = 48;
pub const py_PredefinedType_tp_NameError: py_PredefinedType = 49;
pub const py_PredefinedType_tp_UnboundLocalError: py_PredefinedType = 50;
pub const py_PredefinedType_tp_AttributeError: py_PredefinedType = 51;
pub const py_PredefinedType_tp_ImportError: py_PredefinedType = 52;
pub const py_PredefinedType_tp_AssertionError: py_PredefinedType = 53;
pub const py_PredefinedType_tp_KeyError: py_PredefinedType = 54;
pub const py_PredefinedType_tp_vec2: py_PredefinedType = 55;
pub const py_PredefinedType_tp_vec3: py_PredefinedType = 56;
pub const py_PredefinedType_tp_vec2i: py_PredefinedType = 57;
pub const py_PredefinedType_tp_vec3i: py_PredefinedType = 58;
pub const py_PredefinedType_tp_mat3x3: py_PredefinedType = 59;
pub const py_PredefinedType_tp_color32: py_PredefinedType = 60;
pub const py_PredefinedType_tp_array2d_like: py_PredefinedType = 61;
pub const py_PredefinedType_tp_array2d_like_iterator: py_PredefinedType = 62;
pub const py_PredefinedType_tp_array2d: py_PredefinedType = 63;
pub const py_PredefinedType_tp_array2d_view: py_PredefinedType = 64;
pub const py_PredefinedType_tp_chunked_array2d: py_PredefinedType = 65;
#[doc = " Python favored string formatting.\n %d: int\n %i: py_i64 (int64_t)\n %f: py_f64 (double)\n %s: const char*\n %q: c11_sv\n %v: c11_sv\n %c: char\n %p: void*\n %t: py_Type\n %n: py_Name"]
pub type py_PredefinedType = ::core::ffi::c_uint;
