use std::process::{Command, Output};

#[test]
fn keeps_callback_values_rooted_across_allocation_and_exception_stress() {
    let output = run(
        concat!(
            "import ansi, args, array, base64, binascii, tui, collections, copy, csv, dataclasses, datetime, errno, fnmatch, functools, heapq, input, io, itertools, json, operator, random, secrets, statistics, struct, term, textwrap, typing, uuid\n",
            "spec = {\n",
            "    '--name': str,\n",
            "    '--count': (int, 0),\n",
            "    '--verbose': bool,\n",
            "    '-n': '--name',\n",
            "}\n",
            "retained = []\n",
            "matched_retained = []\n",
            "encoded_retained = []\n",
            "statistic_retained = []\n",
            "heap_retained = []\n",
            "iterator_retained = []\n",
            "operator_retained = []\n",
            "cache_calls = 0\n",
            "@functools.lru_cache(maxsize=32)\n",
            "def cached_pair(value):\n",
            "    global cache_calls\n",
            "    cache_calls += 1\n",
            "    return [value, value + 1]\n",
            "@dataclasses.dataclass\n",
            "class StressPoint:\n",
            "    x: int\n",
            "    y: int = 2\n",
            "for i in range(4000):\n",
            "    parsed = args.parse(spec)\n",
            "    assert parsed['name'] == 'alice'\n",
            "    assert parsed['count'] == 42\n",
            "    assert parsed['verbose'] is True\n",
            "    assert parsed['_'] == ['tail']\n",
            "    retained.append(parsed)\n",
            "    if len(retained) == 32:\n",
            "        for value in retained:\n",
            "            assert value['name'] == 'alice'\n",
            "            assert value['count'] == 42\n",
            "        retained = []\n",
            "    matched = fnmatch.filter(['alpha', 'beta', 'alpine'], 'al*')\n",
            "    assert matched == ['alpha', 'alpine']\n",
            "    matched_retained.append(matched)\n",
            "    if len(matched_retained) == 32:\n",
            "        for value in matched_retained:\n",
            "            assert value == ['alpha', 'alpine']\n",
            "        matched_retained = []\n",
            "    encoded = base64.urlsafe_b64encode(bytes([i % 256, (i + 1) % 256]))\n",
            "    assert base64.urlsafe_b64decode(encoded) == bytes([i % 256, (i + 1) % 256])\n",
            "    assert binascii.unhexlify(binascii.hexlify(encoded)) == encoded\n",
            "    encoded_retained.append(encoded)\n",
            "    if len(encoded_retained) == 32:\n",
            "        for value in encoded_retained:\n",
            "            assert len(value) == 4\n",
            "        encoded_retained = []\n",
            "    average = statistics.mean([i, i + 1, i + 2])\n",
            "    assert average == i + 1\n",
            "    assert statistics.median([i + 2, i, i + 1]) == i + 1\n",
            "    assert statistics.mode([encoded, encoded, b'x']) is encoded\n",
            "    statistic_retained.append(average)\n",
            "    if len(statistic_retained) == 32:\n",
            "        for value in statistic_retained:\n",
            "            assert type(value) is float\n",
            "        statistic_retained = []\n",
            "    heap = [i + 2, i, i + 1]\n",
            "    heapq.heapify(heap)\n",
            "    heapq.heappush(heap, i - 1)\n",
            "    assert heapq.heappop(heap) == i - 1\n",
            "    ranked = heapq.nlargest(2, [i, i + 2, i + 1])\n",
            "    assert ranked == [i + 2, i + 1]\n",
            "    heap_retained.append(ranked)\n",
            "    if len(heap_retained) == 32:\n",
            "        for value in heap_retained:\n",
            "            assert len(value) == 2\n",
            "        heap_retained = []\n",
            "    counter = itertools.count(i, 2)\n",
            "    assert itertools.islice(counter, 1, 5, 2) == [i + 2, i + 6]\n",
            "    assert next(counter) == i + 10\n",
            "    repeated = itertools.repeat(encoded, 2)\n",
            "    assert next(repeated) is encoded\n",
            "    assert next(repeated) is encoded\n",
            "    cycled = itertools.cycle([encoded, ranked])\n",
            "    assert next(cycled) is encoded\n",
            "    assert next(cycled) is ranked\n",
            "    iterator_retained.append(itertools.cycle([encoded]))\n",
            "    if len(iterator_retained) == 32:\n",
            "        for value in iterator_retained:\n",
            "            assert len(next(value)) == 4\n",
            "        iterator_retained = []\n",
            "    assert itertools.chain([i], (i + 1,), 'x') == [i, i + 1, 'x']\n",
            "    assert itertools.takewhile(lambda x: x < 3, [1, 2, 4]) == [1, 2]\n",
            "    assert itertools.dropwhile(lambda x: x < 3, [1, 2, 4]) == [4]\n",
            "    assert errno.errorcode[errno.ENOENT] == 'ENOENT'\n",
            "    assert 'EAGAIN'.isupper() is True\n",
            "    os_error = OSError(i, 'ignored')\n",
            "    assert os_error.args == (i,)\n",
            "    nested = [[i], encoded]\n",
            "    nested_copy = copy.deepcopy(nested)\n",
            "    assert nested_copy == nested and nested_copy is not nested\n",
            "    assert nested_copy[0] is not nested[0]\n",
            "    cycle = []\n",
            "    cycle.append(cycle)\n",
            "    cycle_copy = copy.deepcopy(cycle)\n",
            "    assert cycle_copy is not cycle and cycle_copy[0] is cycle_copy\n",
            "    mutable = bytearray(encoded)\n",
            "    mutable_copy = copy.copy(mutable)\n",
            "    assert mutable_copy == mutable and mutable_copy is not mutable\n",
            "    cached = cached_pair(i % 16)\n",
            "    assert cached_pair(i % 16) is cached\n",
            "    assert cached == [i % 16, i % 16 + 1]\n",
            "    assert functools.reduce(lambda x, y: x + y, [i, 1, 2]) == i + 3\n",
            "    counter_value = collections.Counter([i, i, i + 1])\n",
            "    assert counter_value[i] == 2 and counter_value[i + 1] == 1\n",
            "    csv_output = io.StringIO()\n",
            "    csv.writer(csv_output).writerow([str(i), 'a,b'])\n",
            "    assert list(csv.reader(csv_output.getvalue().split('\\r\\n')[:-1])) == [[str(i), 'a,b']]\n",
            "    point_value = StressPoint(i)\n",
            "    assert dataclasses.is_dataclass(point_value) and point_value.y == 2\n",
            "    assert datetime.date(2024, 1, 15).weekday() == 0\n",
            "    json_value = json.dumps({'b': i + 1, 'a': i}, separators=(',', ':'), sort_keys=True)\n",
            "    assert json.loads(json_value) == {'a': i, 'b': i + 1}\n",
            "    assert 0 <= random.getrandbits(8) < 256\n",
            "    binary_values = array.array('I', [i, i + 1])\n",
            "    binary_data = binary_values.tobytes()\n",
            "    assert struct.unpack('<2I', binary_data) == (i, i + 1)\n",
            "    binary_buffer = bytearray(12)\n",
            "    struct.pack_into('>I', binary_buffer, 4, i)\n",
            "    assert struct.unpack_from('>I', binary_buffer, 4) == (i,)\n",
            "    assert len(secrets.token_bytes(8)) == 8\n",
            "    assert 0 <= secrets.randbelow(17) < 17\n",
            "    uuid_value = uuid.UUID('12345678-1234-4678-9234-567812345678')\n",
            "    assert uuid_value.version == 4 and len(uuid_value.bytes) == 16\n",
            "    picked = operator.itemgetter(0, 1)(([i], [i + 1]))\n",
            "    assert picked == ([i], [i + 1])\n",
            "    operator_retained.append(picked)\n",
            "    if len(operator_retained) == 32:\n",
            "        for value in operator_retained:\n",
            "            assert len(value) == 2 and len(value[0]) == 1\n",
            "        operator_retained = []\n",
            "    hint = typing.TypeVar('T')\n",
            "    assert repr(hint) == '~T'\n",
            "    assert hint.__name__ == 'T'\n",
            "    assert typing.cast(bytes, encoded) is encoded\n",
            "    assert typing.final(ranked) is ranked\n",
            "    assert typing.get_args(hint) == ()\n",
            "    assert typing.get_origin(hint) is None\n",
            "    wrapped = textwrap.wrap('alpha beta gamma', 10)\n",
            "    assert wrapped == ['alpha beta']\n",
            "    assert textwrap.fill('alpha beta gamma', 10) == 'alpha beta\\ngamma'\n",
            "    assert textwrap.dedent('  alpha\\n  beta') == 'alpha\\nbeta'\n",
            "    assert textwrap.indent('alpha\\nbeta', '> ') == '> alpha\\n> beta'\n",
            "    assert textwrap.shorten('alpha beta gamma', 10) == 'alpha...'\n",
            "    styled = tui.style('界', fg='#abc', bold=True)\n",
            "    assert styled == '\\x1b[1;38;2;170;187;204m界\\x1b[0m'\n",
            "    assert tui.visible_len(styled) == 2\n",
            "    expected = '\\x1b[38;2;' + str(i % 256) + ';' + str((i + 1) % 256) + ';' + str((i + 2) % 256) + 'm'\n",
            "    assert ansi.rgb(i, i + 1, i + 2) == expected\n",
            "    assert input.select('', []) is None\n",
            "    assert input.multiselect('', []) == []\n",
            "    assert len(term.size()) == 2\n",
            "    caught = False\n",
            "    try:\n",
            "        args.get('bad index')\n",
            "    except TypeError:\n",
            "        caught = True\n",
            "    assert caught\n",
            "    caught = False\n",
            "    try:\n",
            "        typing.cast(int)\n",
            "    except TypeError:\n",
            "        caught = True\n",
            "    assert caught\n",
            "    caught = False\n",
            "    try:\n",
            "        fnmatch.translate(1)\n",
            "    except TypeError:\n",
            "        caught = True\n",
            "    assert caught\n",
            "    caught = False\n",
            "    try:\n",
            "        binascii.a2b_base64(b'bad')\n",
            "    except ValueError:\n",
            "        caught = True\n",
            "    assert caught\n",
            "    caught = False\n",
            "    try:\n",
            "        statistics.mean([True])\n",
            "    except TypeError:\n",
            "        caught = True\n",
            "    assert caught\n",
            "    caught = False\n",
            "    try:\n",
            "        textwrap.shorten('alpha', 'bad')\n",
            "    except TypeError:\n",
            "        caught = True\n",
            "    assert caught\n",
            "    caught = False\n",
            "    try:\n",
            "        heapq.heappop([])\n",
            "    except IndexError:\n",
            "        caught = True\n",
            "    assert caught\n",
            "    caught = False\n",
            "    try:\n",
            "        itertools.islice([1], 0, 1, 0)\n",
            "    except ValueError:\n",
            "        caught = True\n",
            "    assert caught\n",
            "    caught = False\n",
            "    try:\n",
            "        OSError(1, 2, 3)\n",
            "    except TypeError:\n",
            "        caught = True\n",
            "    assert caught\n",
            "    caught = False\n",
            "    try:\n",
            "        copy.copy()\n",
            "    except TypeError:\n",
            "        caught = True\n",
            "    assert caught\n",
            "    caught = False\n",
            "    try:\n",
            "        functools.reduce(lambda x, y: x + y, [])\n",
            "    except TypeError:\n",
            "        caught = True\n",
            "    assert caught\n",
            "    caught = False\n",
            "    try:\n",
            "        operator.indexOf([1], 2)\n",
            "    except ValueError:\n",
            "        caught = True\n",
            "    assert caught\n",
            "    caught = False\n",
            "    try:\n",
            "        json.loads('[1,]')\n",
            "    except json.JSONDecodeError:\n",
            "        caught = True\n",
            "    assert caught\n",
            "    caught = False\n",
            "    try:\n",
            "        struct.unpack('I', b'\\x00')\n",
            "    except struct.error:\n",
            "        caught = True\n",
            "    assert caught\n",
            "assert len(retained) == 0\n",
            "assert len(matched_retained) == 0\n",
            "assert len(encoded_retained) == 0\n",
            "assert len(statistic_retained) == 0\n",
            "assert len(heap_retained) == 0\n",
            "assert len(iterator_retained) == 0\n",
            "assert len(operator_retained) == 0\n",
            "assert cache_calls == 16",
        ),
        &["--name=alice", "--count", "42", "--verbose", "tail"],
    );

    assert!(output.status.success(), "{}", diagnostic(&output));
    assert_eq!(text(&output.stdout), "");
    assert_eq!(text(&output.stderr), "");
}

#[test]
fn repeatedly_initializes_executes_and_finalizes_the_runtime_process() {
    for cycle in 0..24 {
        let output = run(
            concat!(
                "import args, tui\n",
                "for i in range(100):\n",
                "    assert args.parse({'--value': (int, 7)}) == {'_': [], 'value': 9}\n",
                "    assert tui.spinner_frame(i) == tui.spinner_frame(i + 10)",
            ),
            &["--value=9"],
        );
        assert!(
            output.status.success(),
            "runtime cycle {cycle} failed:\n{}",
            diagnostic(&output)
        );
        assert_eq!(text(&output.stdout), "");
        assert_eq!(text(&output.stderr), "");
    }
}

fn run(source: &str, arguments: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_pocketpy-kipferl"))
        .args(["-c", source])
        .args(arguments)
        .output()
        .expect("run Rust PocketPy runtime")
}

fn text(output: &impl AsRef<[u8]>) -> String {
    String::from_utf8_lossy(output.as_ref()).into_owned()
}

fn diagnostic(output: &Output) -> String {
    format!(
        "status: {}\nstdout:\n{}\nstderr:\n{}",
        output.status,
        text(&output.stdout),
        text(&output.stderr)
    )
}
