"""Case-sensitive filename matching; filter accepts a list."""

from typing import List

def fnmatch(name: str, pattern: str, /) -> bool: ...
def fnmatchcase(name: str, pattern: str, /) -> bool: ...
def filter(names: List[str], pattern: str, /) -> List[str]: ...
def translate(pattern: str, /) -> str: ...
