"""Callable adapters, reduction and cached calls.

partial gives stored keyword arguments precedence over call-time keywords.
Cache wrappers expose cache_info as a plain (hits, misses, maxsize, size) tuple
and cache_clear as a method. wraps copies only __name__ and __doc__.
"""

from typing import Any, Callable, Dict, Iterable, Optional, Tuple

class partial:
    func: Callable[..., Any]
    args: Tuple[Any, ...]
    keywords: Dict[str, Any]
    def __init__(self, f: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

def reduce(function: Callable[[Any, Any], Any], sequence: Iterable[Any], initial: Any = ...) -> Any: ...
def cmp_to_key(compare: Callable[[Any, Any], int]) -> Callable[[Any], Any]: ...
def wraps(wrapped: Callable[..., Any]) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

class _RustLruCacheWrapper:
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def cache_info(self) -> Tuple[int, int, Optional[int], int]: ...
    def cache_clear(self) -> None: ...

def lru_cache(maxsize: Any = 128, typed: bool = False) -> Any:
    """Accept a callable directly, or return a decorator for an int/None size."""
    ...
def cache(function: Callable[..., Any]) -> _RustLruCacheWrapper: ...
