"""In-place heaps and bounded selection for Kipferl lists.

Comparisons may raise Python exceptions, which propagate unchanged. Changing
heap length during a comparison can raise RuntimeError; comparison functions
should leave their input collection unchanged. nlargest/nsmallest accept lists
of at most 256 items for nonzero n, and reject negative n with ValueError.
"""

from typing import List, TypeVar

_T = TypeVar("_T")

def heappush(heap: List[_T], item: _T) -> None: ...
def heappop(heap: List[_T]) -> _T: ...
def heapify(heap: List[_T]) -> None: ...
def heapreplace(heap: List[_T], item: _T) -> _T: ...
def heappushpop(heap: List[_T], item: _T) -> _T: ...
def nlargest(n: int, iterable: List[_T]) -> List[_T]: ...
def nsmallest(n: int, iterable: List[_T]) -> List[_T]: ...
