"""Kipferl's focused iterator API.

count, cycle, and repeat return stateful iterators. chain, islice, takewhile,
and dropwhile eagerly return lists. islice requires nonnegative start/stop
indices and a positive step; its input must be a list, count, or cycle.
Predicates must return bool. Changing the input list length from a predicate
raises RuntimeError; an exception raised by the predicate propagates unchanged.
accumulate and starmap are not provided by this runtime.
"""

from typing import Any, Callable, Iterator, List, Optional, Tuple, TypeVar, Union

_T = TypeVar("_T")

def count(start: int = 0, step: int = 1) -> Iterator[int]: ...
def cycle(iterable: Union[List[_T], str]) -> Iterator[Union[_T, str]]: ...
def repeat(object: _T, times: Optional[int] = None) -> Iterator[_T]: ...
def chain(*iterables: Union[List[Any], Tuple[Any, ...], str]) -> List[Any]: ...
def islice(iterable: Any, *indices: int) -> List[Any]: ...
def takewhile(predicate: Callable[[_T], bool], iterable: List[_T]) -> List[_T]: ...
def dropwhile(predicate: Callable[[_T], bool], iterable: List[_T]) -> List[_T]: ...
