"""Minimal stderr logging and logger metadata.

Module functions write LEVEL: message to stderr. Logger methods apply their
own level; getEffectiveLevel does not inherit the parent's level. Extra message
arguments/keywords, basicConfig options, formatters and handlers do not affect
output. FileHandler stores a filename but does not open or write a file.
"""

from typing import Any, List, Optional

NOTSET: int
DEBUG: int
INFO: int
WARNING: int
WARN: int
ERROR: int
CRITICAL: int
FATAL: int

class Handler:
    level: int
    formatter: Optional["Formatter"]
    def __init__(self) -> None: ...
    def setLevel(self, level: int) -> None: ...
    def setFormatter(self, formatter: "Formatter") -> None: ...

class StreamHandler(Handler): ...

class FileHandler(Handler):
    filename: Optional[str]
    def __init__(self, filename: Optional[str] = None) -> None: ...

class Formatter:
    fmt: Optional[str]
    def __init__(self, fmt: Optional[str] = None) -> None: ...

class Logger:
    name: str
    level: int
    handlers: List[Handler]
    parent: Optional["Logger"]
    def __init__(self, name: str, parent: Optional["Logger"] = None) -> None: ...
    def setLevel(self, level: int) -> None: ...
    def getEffectiveLevel(self) -> int: ...
    def addHandler(self, handler: Handler) -> None: ...
    def debug(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def info(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def error(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def critical(self, message: str, *args: Any, **kwargs: Any) -> None: ...

def getLogger(name: Optional[str] = None) -> Logger: ...
def basicConfig(**kwargs: Any) -> None: ...
def debug(message: str, *args: Any, **kwargs: Any) -> None: ...
def info(message: str, *args: Any, **kwargs: Any) -> None: ...
def warning(message: str, *args: Any, **kwargs: Any) -> None: ...
def error(message: str, *args: Any, **kwargs: Any) -> None: ...
def critical(message: str, *args: Any, **kwargs: Any) -> None: ...
def log(level: int, message: str, *args: Any, **kwargs: Any) -> None: ...
