"""Operator functions and callable item, attribute and method adapters.

itemgetter/attrgetter accept at most 16 selections when called. Attribute path
segments must encode to fewer than 128 bytes. methodcaller and call support at
most 16 positional call arguments. length_hint counts encoded bytes for str,
uses len for lists/tuples, and otherwise returns default without invoking hooks.
Arithmetic results remain dynamic because operands may implement operators.
"""

from typing import Any, Callable, List, Union

class itemgetter:
    def __init__(self, item: Any, *items: Any) -> None: ...
    def __call__(self, obj: Any) -> Any: ...

class attrgetter:
    def __init__(self, attr: str, *attrs: str) -> None: ...
    def __call__(self, obj: Any) -> Any: ...

class methodcaller:
    def __init__(self, name: str, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, obj: Any) -> Any: ...

def call(function: Callable[..., Any], *args: Any, **kwargs: Any) -> Any: ...
def add(a: Any, b: Any) -> Any: ...
def sub(a: Any, b: Any) -> Any: ...
def mul(a: Any, b: Any) -> Any: ...
def truediv(a: Any, b: Any) -> Any: ...
def floordiv(a: Any, b: Any) -> Any: ...
def mod(a: Any, b: Any) -> Any: ...
def pow(a: Any, b: Any) -> Any: ...
def matmul(a: Any, b: Any) -> Any: ...
def and_(a: Any, b: Any) -> Any: ...
def or_(a: Any, b: Any) -> Any: ...
def xor(a: Any, b: Any) -> Any: ...
def lshift(a: Any, b: Any) -> Any: ...
def rshift(a: Any, b: Any) -> Any: ...
def getitem(a: Any, b: Any) -> Any: ...
def iadd(a: Any, b: Any) -> Any: ...
def isub(a: Any, b: Any) -> Any: ...
def imul(a: Any, b: Any) -> Any: ...
def itruediv(a: Any, b: Any) -> Any: ...
def ifloordiv(a: Any, b: Any) -> Any: ...
def imod(a: Any, b: Any) -> Any: ...
def ipow(left: Any, right: Any) -> Any: ...
def iand(a: Any, b: Any) -> Any: ...
def ior(a: Any, b: Any) -> Any: ...
def ixor(a: Any, b: Any) -> Any: ...
def ilshift(a: Any, b: Any) -> Any: ...
def irshift(a: Any, b: Any) -> Any: ...
def neg(a: Any) -> Any: ...
def pos(value: Any) -> Any: ...
def abs(value: Any) -> Any: ...
def invert(a: Any) -> Any: ...
def inv(a: Any) -> Any: ...
def lt(a: Any, b: Any) -> bool: ...
def le(a: Any, b: Any) -> bool: ...
def eq(a: Any, b: Any) -> bool: ...
def ne(a: Any, b: Any) -> bool: ...
def ge(a: Any, b: Any) -> bool: ...
def gt(a: Any, b: Any) -> bool: ...
def is_(a: Any, b: Any) -> bool: ...
def is_not(a: Any, b: Any) -> bool: ...
def contains(a: Any, b: Any) -> bool: ...
def not_(a: Any) -> bool: ...
def truth(a: Any) -> bool: ...
def is_none(value: Any) -> bool: ...
def is_not_none(value: Any) -> bool: ...
def index(value: int) -> int: ...
def concat(left: Union[List[Any], str], right: Union[List[Any], str]) -> Union[List[Any], str]: ...
def iconcat(left: List[Any], right: List[Any]) -> List[Any]: ...
def countOf(sequence: List[Any], value: Any) -> int: ...
def indexOf(sequence: List[Any], value: Any) -> int: ...
def setitem(a: Any, b: Any, c: Any) -> None: ...
def delitem(a: Any, b: Any) -> None: ...
def length_hint(obj: Any, default: int = 0) -> int: ...
