"""Random values and sampling.

seed requires an explicit integer or None. randrange, sample, getrandbits and
string choice use OS randomness and are not controlled by seed; other listed
functions use PocketPy's generator. getrandbits supports 0 through 62 bits.
"""

from typing import Any, List, Optional, Tuple, Union

def seed(value: Optional[int], /) -> None: ...
def random() -> float: ...
def randint(a: int, b: int, /) -> int: ...
def uniform(a: float, b: float, /) -> float: ...
def randrange(start: int, stop: Optional[int] = None, step: int = 1) -> int: ...
def choice(sequence: Union[List[Any], Tuple[Any, ...], str]) -> Any: ...
def shuffle(sequence: List[Any], /) -> None: ...
def sample(population: List[Any], count: int) -> List[Any]: ...
def getrandbits(count: int) -> int: ...
