"""File copying, moving, directory removal and existence checks.

copy and move return the destination path. Destinations are explicit paths;
copy does not automatically append the source name to a directory destination.
"""

def copy(src: str, dst: str, /) -> str: ...
def move(src: str, dst: str, /) -> str: ...
def rmtree(path: str, /) -> None: ...
def exists(path: str, /) -> bool: ...
