"""Basic statistics over lists and tuples.

Numeric operations return floats, including median_low and median_high.
mode returns the first most frequent value using equality comparisons.
Only the functions declared below are provided.
"""

from typing import Any, List, Tuple, Union

_Data = Union[List[float], Tuple[float, ...]]

def mean(data: _Data, /) -> float: ...
def median(data: _Data, /) -> float: ...
def median_low(data: _Data, /) -> float: ...
def median_high(data: _Data, /) -> float: ...
def mode(data: Union[List[Any], Tuple[Any, ...]], /) -> Any: ...
def variance(data: _Data, /) -> float: ...
def pvariance(data: _Data, /) -> float: ...
def stdev(data: _Data, /) -> float: ...
def pstdev(data: _Data, /) -> float: ...
