"""Basic wrapping, indentation and whitespace shortening."""

from typing import List

def wrap(text: str, width: int = 70) -> List[str]: ...
def fill(text: str, width: int = 70) -> str: ...
def dedent(text: str, /) -> str: ...
def indent(text: str, prefix: str, /) -> str: ...
def shorten(text: str, width: int, /) -> str: ...
