[package]
name = "ucharm-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libc = "0.2"
ucharm-pocketpy-sys = { path = "../pocketpy-sys" }

[lints]
workspace = true

[[bin]]
name = "pocketpy-ucharm-rs"
path = "src/main.rs"
