use std::io::{self, Write};

pub fn execute(
    arguments: &[String],
    stdout: &mut dyn Write,
    stderr: &mut dyn Write,
) -> io::Result<u8> {
    if matches!(arguments, [argument] if matches!(argument.as_str(), "-h" | "--help")) {
        writeln!(
            stdout,
            "Usage: kipferl completions <bash|zsh|fish>\n\nPrint shell completions to stdout. Install with:\n  kipferl completions bash > ~/.kipferl-completion.bash\n  source ~/.kipferl-completion.bash\n  kipferl completions zsh > ~/.kipferl-completion.zsh\n  source ~/.kipferl-completion.zsh\n  kipferl completions fish > ~/.config/fish/completions/kipferl.fish"
        )?;
        return Ok(0);
    }
    let shell = match arguments {
        [argument] => argument.as_str(),
        _ => "",
    };
    let script = match shell {
        "bash" => BASH,
        "zsh" => ZSH,
        "fish" => FISH,
        _ => {
            writeln!(
                stderr,
                "Error: expected one shell: bash, zsh, or fish. Run 'kipferl completions --help' for installation."
            )?;
            return Ok(1);
        }
    };
    write!(stdout, "{script}")?;
    Ok(0)
}

const BASH: &str = r#"# Generated by kipferl completions bash
_kipferl() {
    local cur="${COMP_WORDS[COMP_CWORD]}" prev="${COMP_WORDS[COMP_CWORD-1]}"
    local choices=""
    case "$prev" in
        --template) choices="cli api interactive" ;;
        --ai) choices="agents claude copilot all" ;;
        --mode|-m) [[ "${COMP_WORDS[1]}" == build ]] && choices="universal executable single" ;;
        --target|-t) choices="macos-aarch64 macos-x86_64 linux-aarch64 linux-x86_64" ;;
        completions) choices="bash zsh fish" ;;
        deps) choices="check list catalog audit --help" ;;
    esac
    if [[ $COMP_CWORD == 1 ]]; then
        choices="new init run dev build test add sync deps completions --help --version"
    elif [[ -z "$choices" && "$cur" == -* ]]; then
        case "${COMP_WORDS[1]}" in
            new) choices="--template --minimal --stubs --ai --all --help" ;;
            init) choices="--stubs --ai --all --help" ;;
            build) choices="--output --mode --target --asset --targets --full-runtime --help" ;;
            dev) choices="--watch --clear --debounce --help" ;;
            add) choices="--allow-unverified --help" ;;
            sync) choices="--locked --offline --help" ;;
            deps) choices="--json --limit --help" ;;
            test) choices="--compat --report --verbose --module --help" ;;
            *) choices="--help" ;;
        esac
    fi
    if [[ -n "$choices" ]]; then
        COMPREPLY=( $(compgen -W "$choices" -- "$cur") )
    else
        COMPREPLY=( $(compgen -f -- "$cur") )
    fi
}
complete -o filenames -F _kipferl kipferl
"#;

const ZSH: &str = r#"# Generated by kipferl completions zsh
# Source after compinit (or save as _kipferl in a directory on fpath).
autoload -Uz compinit
(( $+functions[compdef] )) || compinit
_kipferl() {
    local -a commands
    commands=('new:Create a project' 'init:Add editor support' 'run:Run a script' 'dev:Watch and restart' 'build:Build a standalone app' 'test:Run tests' 'add:Add a PyPI dependency' 'sync:Restore locked dependencies' 'deps:Check packages and compatibility catalog' 'completions:Generate shell completions')
    if (( CURRENT == 2 )); then
        _describe 'command' commands
        return
    fi
    case "$words[CURRENT-1]" in
        --template) compadd cli api interactive; return ;;
        --ai) compadd agents claude copilot all; return ;;
        --mode|-m) if [[ "$words[2]" == build ]]; then compadd universal executable single; return; fi ;;
        --target|-t) compadd macos-aarch64 macos-x86_64 linux-aarch64 linux-x86_64; return ;;
        completions) compadd bash zsh fish; return ;;
        deps) compadd check list catalog audit; return ;;
    esac
    case "$words[2]" in
        new) _arguments '--template[Starter template]:template:(cli api interactive)' '--minimal[Create only a script]' '--stubs[Add editor stubs]' '--ai[AI instructions]:type:(agents claude copilot all)' '--all[Add editor and AI support]' '--help[Show help]' '*:name:' ;;
        init) _arguments '--stubs[Add editor stubs]' '--ai[AI instructions]:type:(agents claude copilot all)' '--all[Add editor and AI support]' '--help[Show help]' ;;
        build) _arguments '--output[Output path]:path:_files' '*--asset[Bundle a path]:path:_files' '--mode[Build mode]:mode:(universal executable single)' '--target[Target platform]:target:(macos-aarch64 macos-x86_64 linux-aarch64 linux-x86_64)' '--full-runtime[Include all modules]' '--targets[List targets]' '--help[Show help]' '*:script:_files' ;;
        dev) _arguments '*--watch[Watch a path]:path:_files' '--clear[Clear terminal]' '--debounce[Debounce milliseconds]:milliseconds:' '--help[Show help]' '*:script:_files' ;;
        add) _arguments '--allow-unverified[Accept packages without matching compatibility tests]' '--help[Show help]' '*:requirement:' ;;
        sync) _arguments '--locked[Restore exact locked packages]' '--offline[Use cached wheels only]' '--help[Show help]' ;;
        deps) _arguments '--limit[Maximum audit rows]:rows:' '--json[Machine-readable evidence]' '--help[Show help]' ;;
        test) _arguments '--compat[Compatibility suite]' '--report[Write compatibility report]' '--verbose[Verbose compatibility results]' '--module[Compatibility module]:module:' '--help[Show help]' '*:test:_files' ;;
        *) _files ;;
    esac
}
compdef _kipferl kipferl
"#;

const FISH: &str = r"# Generated by kipferl completions fish
complete -c kipferl -n '__fish_use_subcommand' -a 'new init run dev build test add sync deps completions'
complete -c kipferl -s h -l help -d 'Show help'
complete -c kipferl -n '__fish_use_subcommand' -l version -d 'Show version'
complete -c kipferl -n '__fish_seen_subcommand_from new' -l template -x -a 'cli api interactive'
complete -c kipferl -n '__fish_seen_subcommand_from new' -l minimal -d 'Create only a script'
complete -c kipferl -n '__fish_seen_subcommand_from new init' -l stubs -d 'Add editor stubs'
complete -c kipferl -n '__fish_seen_subcommand_from new init' -l ai -x -a 'agents claude copilot all'
complete -c kipferl -n '__fish_seen_subcommand_from new init' -l all -d 'Add editor and AI support'
complete -c kipferl -n '__fish_seen_subcommand_from build' -s o -l output -r
complete -c kipferl -n '__fish_seen_subcommand_from build' -l asset -r
complete -c kipferl -n '__fish_seen_subcommand_from build' -s m -l mode -x -a 'universal executable single'
complete -c kipferl -n '__fish_seen_subcommand_from build' -s t -l target -x -a 'macos-aarch64 macos-x86_64 linux-aarch64 linux-x86_64'
complete -c kipferl -n '__fish_seen_subcommand_from build' -l targets
complete -c kipferl -n '__fish_seen_subcommand_from build' -l full-runtime
complete -c kipferl -n '__fish_seen_subcommand_from dev' -s w -l watch -r
complete -c kipferl -n '__fish_seen_subcommand_from dev' -l clear
complete -c kipferl -n '__fish_seen_subcommand_from dev' -l debounce -x
complete -c kipferl -n '__fish_seen_subcommand_from test' -l compat
complete -c kipferl -n '__fish_seen_subcommand_from test' -s r -l report
complete -c kipferl -n '__fish_seen_subcommand_from test' -s v -l verbose
complete -c kipferl -n '__fish_seen_subcommand_from test' -s m -l module -x
complete -c kipferl -n '__fish_seen_subcommand_from add' -l allow-unverified -d 'Accept unverified packages'
complete -c kipferl -n '__fish_seen_subcommand_from sync' -l locked
complete -c kipferl -n '__fish_seen_subcommand_from sync' -l offline
complete -c kipferl -n '__fish_seen_subcommand_from deps; and __fish_seen_subcommand_from catalog audit' -l json -d 'Full catalog evidence'
complete -c kipferl -n '__fish_seen_subcommand_from deps; and __fish_seen_subcommand_from audit' -l limit -x -d 'Maximum audit rows'
complete -c kipferl -n '__fish_seen_subcommand_from deps' -f -a 'check list catalog audit'
complete -c kipferl -n '__fish_seen_subcommand_from completions' -f -a 'bash zsh fish'
";
