#!/usr/bin/env python3
"""Generate and validate Kipferl's canonical Python stub manifest.

The hand-authored ``stubs/*.pyi`` files are the single source of truth. This
script verifies that every stub names a registered Rust runtime module, then
generates the small Rust manifest that embeds every canonical stub in the CLI.
It can also copy the canonical set into another directory for tools or
packaging workflows.

Usage:
    python3 scripts/generate_stubs.py
    python3 scripts/generate_stubs.py --check
    python3 scripts/generate_stubs.py --output /tmp/kipferl-stubs
    python3 scripts/generate_stubs.py --check --output /tmp/kipferl-stubs
"""

from __future__ import annotations

import argparse
import ast
import difflib
import re
import sys
from dataclasses import dataclass
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
CANONICAL_DIRECTORY = PROJECT_ROOT / "stubs"
RUST_MANIFEST = PROJECT_ROOT / "crates/kipferl-cli/src/generated_stubs.rs"
RUNTIME_REGISTRY = PROJECT_ROOT / "crates/kipferl-runtime/src/modules/mod.rs"
MODULE_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


@dataclass(frozen=True)
class Stub:
    filename: str
    content: str


class StubError(ValueError):
    """Raised when the canonical stub set is invalid."""


def load_stubs(directory: Path = CANONICAL_DIRECTORY) -> tuple[Stub, ...]:
    """Load and validate the canonical stubs in deterministic order."""
    if not directory.is_dir():
        raise StubError(f"stub directory does not exist: {directory}")

    stubs = []
    for path in sorted(directory.glob("*.pyi"), key=lambda item: item.name):
        if not MODULE_NAME.fullmatch(path.stem):
            raise StubError(f"invalid Python module filename: {path.name}")

        content = path.read_text(encoding="utf-8")
        if not content.endswith("\n"):
            raise StubError(f"{path.name} must end with a newline")
        try:
            ast.parse(content, filename=str(path))
        except SyntaxError as error:
            raise StubError(f"invalid Python syntax in {path.name}: {error}") from error
        stubs.append(Stub(path.name, content))

    if not stubs:
        raise StubError(f"no .pyi files found in {directory}")
    return tuple(stubs)


def load_registered_modules(registry: Path = RUNTIME_REGISTRY) -> frozenset[str]:
    """Read the public module names from the Rust runtime registry."""
    content = registry.read_text(encoding="utf-8")
    match = re.search(r"const MODULES:.*?=\s*&\[(.*?)\];", content, re.DOTALL)
    if match is None:
        raise StubError(f"could not find the runtime module registry in {registry}")

    identifiers = re.findall(
        r"^\s*([A-Za-z_][A-Za-z0-9_]*)::MODULE,", match.group(1), re.MULTILINE
    )
    if not identifiers:
        raise StubError(f"runtime module registry is empty in {registry}")

    modules = set()
    module_directory = registry.parent
    for identifier in identifiers:
        source = module_directory / f"{identifier}.rs"
        module_content = source.read_text(encoding="utf-8")
        name_match = re.search(
            r"pub\(super\)\s+const\s+MODULE:.*?\{.*?name:\s*c\"([^\"]+)\"",
            module_content,
            re.DOTALL,
        )
        if name_match is None:
            raise StubError(f"could not find NativeModule.name in {source}")
        modules.add(name_match.group(1))
    return frozenset(modules)


def validate_runtime_modules(
    stubs: tuple[Stub, ...], registered_modules: frozenset[str]
) -> None:
    """Reject editor APIs for modules that the runtime cannot import."""
    unsupported = sorted(
        stub.filename.removesuffix(".pyi")
        for stub in stubs
        if stub.filename.removesuffix(".pyi") not in registered_modules
    )
    if unsupported:
        raise StubError(f"stubs have no registered Rust runtime module: {unsupported}")


def render_rust_manifest(stubs: tuple[Stub, ...]) -> str:
    """Render the checked-in Rust include manifest."""
    lines = [
        "// @generated by scripts/generate_stubs.py; DO NOT EDIT.",
        "// Canonical sources live in the repository root stubs/ directory.",
        "",
        "pub const STUBS: &[(&str, &str)] = &[",
    ]
    for stub in stubs:
        lines.append(
            f'    ("{stub.filename}", include_str!("../../../stubs/{stub.filename}")),'
        )
    lines.extend(["];"])
    return "\n".join(lines) + "\n"


def unified_diff(expected: str, actual: str, destination: Path) -> str:
    """Return a readable diff for a stale generated file."""
    return "".join(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=str(destination),
            tofile=f"generated:{destination}",
        )
    )


def check_manifest(expected: str, destination: Path = RUST_MANIFEST) -> None:
    """Fail when the checked-in Rust manifest is missing or stale."""
    actual = destination.read_text(encoding="utf-8") if destination.exists() else ""
    if actual != expected:
        diff = unified_diff(expected, actual, destination)
        raise StubError(
            f"generated stub manifest is stale; run scripts/generate_stubs.py\n{diff}"
        )


def write_manifest(content: str, destination: Path = RUST_MANIFEST) -> None:
    """Write the deterministic Rust manifest."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8")


def check_output(stubs: tuple[Stub, ...], output: Path) -> None:
    """Fail when an exported stub directory differs from the canonical set."""
    expected_names = {stub.filename for stub in stubs}
    actual_names = {path.name for path in output.glob("*.pyi")} if output.is_dir() else set()
    if actual_names != expected_names:
        missing = sorted(expected_names - actual_names)
        extra = sorted(actual_names - expected_names)
        raise StubError(f"stub export drift in {output}: missing={missing}, extra={extra}")

    for stub in stubs:
        destination = output / stub.filename
        actual = destination.read_text(encoding="utf-8")
        if actual != stub.content:
            raise StubError(
                f"stub export drift in {destination}\n"
                + unified_diff(stub.content, actual, destination)
            )


def write_output(stubs: tuple[Stub, ...], output: Path) -> None:
    """Synchronize an exported directory to the canonical stub set."""
    if output.resolve() == CANONICAL_DIRECTORY.resolve():
        return
    output.mkdir(parents=True, exist_ok=True)
    expected_names = {stub.filename for stub in stubs}
    for stale in output.glob("*.pyi"):
        if stale.name not in expected_names:
            stale.unlink()
    for stub in stubs:
        (output / stub.filename).write_text(stub.content, encoding="utf-8")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated files without changing them",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="also synchronize or verify a directory containing the canonical .pyi files",
    )
    return parser.parse_args(argv)


def run(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        stubs = load_stubs()
        validate_runtime_modules(stubs, load_registered_modules())
        manifest = render_rust_manifest(stubs)
        if args.check:
            check_manifest(manifest)
            if args.output is not None:
                check_output(stubs, args.output)
            action = "Verified"
        else:
            write_manifest(manifest)
            if args.output is not None:
                write_output(stubs, args.output)
            action = "Generated"
    except (OSError, StubError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    suffix = f" and {args.output}" if args.output is not None else ""
    print(f"{action} {len(stubs)} canonical stubs in {RUST_MANIFEST}{suffix}")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
